export const elements = {
    get dropZone() { return document.getElementById('dropZone'); },
    get fileInput() { return document.getElementById('fileInput'); },
    get filesList() { return document.getElementById('filesList'); },
    get actions() { return document.getElementById('actions'); },
    get processBtn() { return document.getElementById('processBtn'); },
    get clearBtn() { return document.getElementById('clearBtn'); },
    get progressSection() { return document.getElementById('progressSection'); },
    get progressFill() { return document.getElementById('progressFill'); },
    get progressText() { return document.getElementById('progressText'); },
    get resultsSection() { return document.getElementById('resultsSection'); },
    get resultsStats() { return document.getElementById('resultsStats'); },
    get downloadBtn() { return document.getElementById('downloadBtn'); },
    get downloadBtnText() { return document.getElementById('downloadBtnText'); },
    get packsActivation() { return document.getElementById('packsActivation'); },
    get selectAllBtn() { return document.getElementById('selectAllBtn'); },
    get deselectAllBtn() { return document.getElementById('deselectAllBtn'); },
    get worldInfo() { return document.getElementById('worldInfo'); },
    get worldName() { return document.getElementById('worldName'); },
    get worldManagement() { return document.getElementById('worldManagement'); },
    get additionalAddons() { return document.getElementById('additionalAddons'); },
    get additionalAddonsList() { return document.getElementById('additionalAddonsList'); },
    get resultsTitle() { return document.getElementById('resultsTitle'); },
    get activationTitle() { return document.getElementById('activationTitle'); },
    get activationDescription() { return document.getElementById('activationDescription'); }
};
